<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <PackageProjectUrl>https://github.com/Ryukote/KeycloakStandard</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Ryukote/KeycloakStandard</RepositoryUrl>
    <Authors>Antonio Halužan</Authors>
    <Company />
    <Description>Keycloak client for .NET Standard (Test version).</Description>
    <AssemblyVersion>1.1.0.1</AssemblyVersion>
    <FileVersion>1.1.0.1</FileVersion>
    <Version>1.0.9</Version>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
